version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # or another supported version
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - mkdir -p dist
      - cp -R .next dist
      - cp package*.json dist
      - cp -R public dist
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'